FROM ubuntu:20.04

ENV PERFORCE_DEPOT https://cdist2.perforce.com/perforce/tools/sampledepot.tar.gz
ENV PERFORCE_DATA_DIR /p4
ENV PERFORCE_VER r22.1

# Perforce Environment Variables
ENV P4PORT 1666
ENV P4ROOT $PERFORCE_DATA_DIR/PerforceSample

RUN apt update -y; \
    apt install -y curl rsync sudo wget; \
    echo /usr/local/lib >> /etc/ld.so.conf; \
    echo /usr/lib64 >> /etc/ld.so.conf; \
    sed -ie "s/^Defaults[ \t]*requiretty/#Defaults  requiretty/g" /etc/sudoers

# Download Perforce binaries
ADD https://cdist2.perforce.com/perforce/$PERFORCE_VER/bin.linux26x86_64/p4d /usr/local/bin/p4d
ADD https://cdist2.perforce.com/perforce/$PERFORCE_VER/bin.linux26x86_64/p4 /usr/local/bin/p4
RUN chmod +x /usr/local/bin/p4*

# Set working directory
WORKDIR $PERFORCE_DATA_DIR

# Download and extract sample depot
RUN curl -sSL $PERFORCE_DEPOT > sampledepot.tar.gz && tar xvf sampledepot.tar.gz

# Restore journal & upgrade db(s)
WORKDIR $PERFORCE_DATA_DIR/PerforceSample
RUN p4d -r . -jr ./checkpoint

# Upgrade database to current p4d binary version
RUN p4d -r . -xu

# Run as unicode
RUN p4d -r . -xi

RUN p4d -r . -xD "perforce-master"

RUN apt install -y openssh-server openssh-client passwd; \
    apt clean; \
    ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''; \
    ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ''

RUN apt install -y python python3 python3-dev python3-pip openssl libssl-dev;

# Let's start Perforce
ENTRYPOINT ["p4d"]
CMD ["-A", "STDOUT", "-L", "STDOUT"]
