---
dependency:
  name: galaxy
  enabled: False
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: rockylinux9-23.1
    dockerfile: Dockerfile.rockylinux.9-23.1.j2
    image: rockylinux.9-23.1
    command: '-r .'
  - name: rockylinux9-23.2
    dockerfile: Dockerfile.rockylinux.9-23.2.j2
    image: rockylinux.9-23.2
    command: '-r .'
  - name: rockylinux9-24.1
    dockerfile: Dockerfile.rockylinux.9-24.1.j2
    image: rockylinux.9-24.1
    command: '-r .'
  - name: rockylinux9-24.2
    dockerfile: Dockerfile.rockylinux.9-24.2.j2
    image: rockylinux.9-24.2
    command: '-r .'
  - name: ubuntu2004-23.1
    dockerfile: Dockerfile.ubuntu.20.04-23.1.j2
    image: ubuntu:20.04-23.1
    command: '-r .'
  - name: ubuntu2004-23.2
    dockerfile: Dockerfile.ubuntu.20.04-23.2.j2
    image: ubuntu:20.04-23.2
    command: '-r .'
  - name: ubuntu2204-23.1
    dockerfile: Dockerfile.ubuntu.22.04-23.1.j2
    image: ubuntu:22.04-23.1
    command: '-r .'
  - name: ubuntu2204-23.2
    dockerfile: Dockerfile.ubuntu.22.04-23.2.j2
    image: ubuntu:22.04-23.2
    command: '-r .'
  - name: ubuntu2204-24.1
    dockerfile: Dockerfile.ubuntu.22.04-24.1.j2
    image: ubuntu:22.04-24.1
    command: '-r .'
  - name: ubuntu2204-24.2
    dockerfile: Dockerfile.ubuntu.22.04-24.2.j2
    image: ubuntu:22.04-24.2
    command: '-r .'
provisioner:
  name: ansible
  log: true
  # options:
  #   vvv: true
  env:
    ANSIBLE_COLLECTIONS_PATHS: "/home/runner/work/ansible-collection-helix-core/ansible-collection-helix-core:~/.ansible/collections"
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: "/usr/bin/python3"
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - destroy
